import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaHome, FaUser, FaSignOutAlt, FaBook } from "react-icons/fa"; // Dodano ikonę dla Artykułów
import Link from "next/link";
import { AuthProvider } from "./lib/AuthContext.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="flex h-screen">
            {/* Pasek boczny */}
            <aside className="w-64 bg-gray-800 text-white flex flex-col p-4">
              <nav className="flex flex-col gap-4">
               
                <Link
                  href="/protected/user/profile"
                  className="flex items-center gap-3 hover:bg-gray-700 p-2 rounded"
                >
                  <FaUser />
                  <span>Profile</span>
                </Link>
                <Link
                  href="/protected/user/signout"
                  className="flex items-center gap-3 hover:bg-gray-700 p-2 rounded"
                >
                  <FaSignOutAlt />
                  <span>Logout</span>
                </Link>
                <Link
                  href="/articles"
                  className="flex items-center gap-3 hover:bg-gray-700 p-2 rounded"
                >
                  <FaBook />
                  <span>Articles</span>
                </Link>
              </nav>
            </aside>

            {/* Główna zawartość */}
            <div className="flex-1 flex flex-col">
              {/* Górny pasek */}
              <header className="bg-gray-100 flex justify-between items-center px-6 py-4 shadow-md">
                <h1 className="text-xl font-semibold">Global App Layout</h1>
                <div className="flex gap-4">
                  <Link
                    href="/public/user/signin"
                    className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
                  >
                    Sign In
                  </Link>
                  <Link
                    href="/public/user/register"
                    className="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600"
                  >
                    Register
                  </Link>
                </div>
              </header>

              {/* Dynamiczna treść */}
              <main className="flex-1 p-6 bg-gray-50 overflow-auto">
                {children}
              </main>

              {/* Stopka */}
              <footer className="bg-gray-200 text-center py-4">
                <p>© 2025 Your App. All rights reserved.</p>
              </footer>
            </div>
          </div>
        </AuthProvider>

        {/* Preline UI Script */}
        <script src="./node_modules/preline/dist/preline.js"></script>
      </body>
    </html>
  );
}
